# Dependencies
highlighter:      rouge
gems:
    - jekyll-gist
    - jekyll-paginate
    - jekyll-mentions

# Permalinks
permalink:        pretty

# Setup
title:            datreant
tagline:          'persistent, pythonic trees for heterogeneous data'
description:      'persistent, pythonic trees for heterogeneous data'
url:              http://datreant.org
baseurl:          /
blog:             /blog

author:
#  name:           'datreant development team'
#  url:            

# Custom vars
#version:          2.1.0
#
# Blog pagination
paginate_path:   "/blog/page:num/"
paginate:        3

docs:
  core:           http://datreant.readthedocs.org/

maillist:         http://groups.google.com/group/datreant

github:
  org:            https://github.com/datreant
  core:           https://github.com/datreant/datreant.core
  data:           https://github.com/datreant/datreant.data
  mdsynthesis:    https://github.com/datreant/MDSynthesis
